import streamlit as st
import pandas as pd
import sqlite3
import hashlib
import os
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import joblib
import io

# PDF Generation
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch

# =====================================================
# PAGE CONFIG & THEME
# =====================================================
st.set_page_config(page_title="NephroAI | Clinical Hospital System", layout="wide", page_icon="🏥")

st.markdown("""
<style>
    .main { background-color: #f8f9fa; }
    .stButton>button { width: 100%; border-radius: 5px; height: 3em; background-color: #004a99; color: white; font-weight: bold; }
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
    [data-testid="stSidebar"] { background-color: #002b5c; }
    [data-testid="stSidebar"] * { color: white !important; }
</style>
""", unsafe_allow_html=True)

# =====================================================
# DATABASE SYSTEM
# =====================================================
DB_FILE = "ckd_hospital_v2.db"

def init_db():
    conn = sqlite3.connect(DB_FILE, check_same_thread=False)
    cursor = conn.cursor()
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS users(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT UNIQUE, password TEXT, role TEXT, phone TEXT, created_at TEXT
    )""")
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS predictions(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT, model_used TEXT, probability REAL, prediction INTEGER,
        visit_number INTEGER, next_visit TEXT, created_at TEXT,
        age INTEGER, bp INTEGER, bgr INTEGER, bu INTEGER, sc REAL, hemo REAL
    )""")
    conn.commit()
    return conn, cursor

conn, cursor = init_db()

# =====================================================
# UTILITIES & ML LOADING
# =====================================================
def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

@st.cache_resource
def load_assets():
    model = joblib.load("ckd_random_forest.pkl") if os.path.exists("ckd_random_forest.pkl") else None
    scaler = joblib.load("scaler.pkl") if os.path.exists("scaler.pkl") else None
    return model, scaler

rf_model, scaler = load_assets()

def calculate_followup(prob, username):
    visit_count = cursor.execute("SELECT COUNT(*) FROM predictions WHERE username=?", (username,)).fetchone()[0]
    percent = prob * 100
    days = 180 if percent < 30 else (30 if percent < 70 else 7)
    next_visit = datetime.now() + timedelta(days=days)
    return visit_count + 1, next_visit.date()

# =====================================================
# PDF REPORT GENERATOR
# =====================================================
def generate_medical_pdf(username, prob, next_visit, metrics):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("OFFICIAL NEPHROLOGY ANALYSIS REPORT", styles["Title"]))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(f"Patient ID: {username}", styles["Normal"]))
    elements.append(Paragraph(f"Analysis Date: {datetime.now().strftime('%Y-%m-%d')}", styles["Normal"]))
    elements.append(Spacer(1, 12))

    data = [["Clinical Parameter", "Value"],
            ["Age", metrics['age']],
            ["Blood Pressure", f"{metrics['bp']} mmHg"],
            ["Serum Creatinine", f"{metrics['sc']} mg/dl"],
            ["Hemoglobin", f"{metrics['hemo']} g/dL"],
            ["AI Risk Probability", f"{prob*100:.2f}%"]]
    
    t = Table(data, colWidths=[2.5*inch, 2*inch])
    t.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, 0), colors.dodgerblue),
                           ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                           ('GRID', (0,0), (-1,-1), 1, colors.grey)]))
    elements.append(t)
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(f"Recommended Follow-up: {next_visit}", styles["Heading3"]))
    elements.append(Paragraph("Note: This report is generated by an AI system and should be reviewed by a clinician.", styles["Italic"]))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer

# =====================================================
# LOGIN / REGISTER UI
# =====================================================
def auth_page():
    col1, col2 = st.columns([1, 1])
    with col1:
        st.image("https://cdn-icons-png.flaticon.com/512/2966/2966327.png", width=150)
        st.title("NephroAI Hospital System")
        st.write("Secure Clinical Portal for AI-Driven Kidney Disease Monitoring.")
    
    with col2:
        tab1, tab2 = st.tabs(["Login", "Register"])
        with tab1:
            u = st.text_input("Username", key="l_u")
            p = st.text_input("Password", type="password", key="l_p")
            if st.button("Sign In"):
                user = cursor.execute("SELECT * FROM users WHERE username=? AND password=?", (u, hash_password(p))).fetchone()
                if user:
                    st.session_state.logged_in = True
                    st.session_state.username, st.session_state.role = user[1], user[3]
                    st.rerun()
                else: st.error("Invalid Credentials")
        with tab2:
            new_u = st.text_input("New Username")
            new_p = st.text_input("New Password", type="password")
            role = st.selectbox("Role", ["patient", "doctor"])
            phone = st.text_input("Phone Number")
            if st.button("Register Account"):
                try:
                    cursor.execute("INSERT INTO users(username,password,role,phone,created_at) VALUES(?,?,?,?,?)",
                                 (new_u, hash_password(new_p), role, phone, str(datetime.now())))
                    conn.commit()
                    st.success("Registration Successful! Please Login.")
                except: st.error("Username already exists.")

# =====================================================
# PATIENT INTERFACE (ALL 24 FEATURES)
# =====================================================
def patient_page():
    st.sidebar.title(f"Patient: {st.session_state.username}")
    if st.sidebar.button("Logout"):
        st.session_state.logged_in = False
        st.rerun()

    st.title("🏥 Kidney Risk Assessment")
    
    # --- INFORMATION HEADER ---
    with st.expander("ℹ️ Clinical Guidelines: Before you enter data"):
        st.write("""
        This analysis requires data from your **Complete Blood Count (CBC)** and **Urine Routine Examination**.
        Hover over the **(?)** icons for specific medical context.
        """)

    # --- MAIN DATA ENTRY FORM ---
    with st.form("comprehensive_form"):
        st.subheader("📝 Lab Report Parameters")
        
        c1, c2, c3, c4 = st.columns(4)
        with c1:
            age = st.number_input("Age", 1, 120, 45)
            bp = st.number_input("Blood Pressure", 50, 200, 120, help="Systolic BP")
            sg = st.selectbox("Specific Gravity", [1.005, 1.010, 1.015, 1.020, 1.025], index=3)
        with c2:
            al = st.selectbox("Albumin (0-5)", [0, 1, 2, 3, 4, 5])
            su = st.selectbox("Sugar (0-5)", [0, 1, 2, 3, 4, 5])
            rbc = st.selectbox("RBC in Urine", ["normal", "abnormal"])
        with c3:
            pc = st.selectbox("Pus Cells", ["normal", "abnormal"])
            pcc = st.selectbox("Pus Cell Clumps", ["present", "notpresent"])
            ba = st.selectbox("Bacteria", ["present", "notpresent"])
        with c4:
            bgr = st.number_input("Blood Glucose", 50, 500, 121)
            bu = st.number_input("Blood Urea", 1, 400, 36)
            sc = st.number_input("Serum Creatinine", 0.1, 20.0, 1.2, help="Crucial for Kidney function")

        st.divider()
        
        c5, c6, c7, c8 = st.columns(4)
        with c5:
            sod = st.number_input("Sodium", 100, 180, 137)
            pot = st.number_input("Potassium", 2.0, 10.0, 4.6)
        with c6:
            hemo = st.number_input("Hemoglobin", 3.0, 20.0, 12.5)
            pcv = st.number_input("Packed Cell Volume", 10, 60, 40)
        with c7:
            wc = st.number_input("WBC Count", 2000, 25000, 8000)
            rc = st.number_input("RBC Count", 2.0, 8.0, 4.7)
        with c8:
            htn = st.selectbox("Hypertension", ["yes", "no"])
            dm = st.selectbox("Diabetes", ["yes", "no"])

        st.divider()
        
        h1, h2, h3, h4 = st.columns(4)
        with h1: cad = st.selectbox("CAD Disease", ["yes", "no"])
        with h2: appet = st.selectbox("Appetite", ["good", "poor"])
        with h3: pe = st.selectbox("Pedal Edema", ["yes", "no"])
        with h4: ane = st.selectbox("Anemia", ["yes", "no"])

        submit = st.form_submit_button("🚀 GENERATE AI ANALYSIS")

    if submit:
        if rf_model and scaler:
            # Logic Mapping
            mapping = {"yes": 1, "no": 0, "normal": 1, "abnormal": 0, "present": 1, "notpresent": 0, "good": 1, "poor": 0}
            
            # Prepare All Features (The Mapping logic you need)
            user_data = {
                "age": age, "bp": bp, "sg": sg, "al": al, "su": su, "rbc": mapping[rbc], "pc": mapping[pc],
                "pcc": mapping[pcc], "ba": mapping[ba], "bgr": bgr, "bu": bu, "sc": sc, "sod": sod,
                "pot": pot, "hemo": hemo, "pcv": pcv, "wc": wc, "rc": rc, "htn": mapping[htn],
                "dm": mapping[dm], "cad": mapping[cad], "appet": mapping[appet], "pe": mapping[pe], "ane": mapping[ane]
            }

            # Align with Model features
            features = scaler.feature_names_in_
            df_final = pd.DataFrame([user_data])[features]
            scaled_input = scaler.transform(df_final)
            prob = rf_model.predict_proba(scaled_input)[0][1]

            # Results Display
            st.markdown("---")
            v_col1, v_col2 = st.columns([1, 2])
            
            with v_col1:
                st.metric("Risk Level", f"{prob*100:.1f}%")
                if prob > 0.7: st.error("High Risk: Seek immediate medical care.")
                elif prob > 0.3: st.warning("Moderate Risk: Monitor and consult a doctor.")
                else: st.success("Low Risk: Your profile looks healthy.")

            with v_col2:
                

# Image of stages of chronic kidney disease and GFR levels

                st.info("The AI compares your 24 clinical markers against thousands of hospital records.")

            # Database & Follow-up
            v_num, next_v = calculate_followup(prob, st.session_state.username)
            cursor.execute("""INSERT INTO predictions 
                (username, model_used, probability, prediction, visit_number, next_visit, created_at, age, bp, bgr, bu, sc, hemo)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)""", 
                (st.session_state.username, "Random Forest", prob, 1 if prob > 0.5 else 0, v_num, str(next_v), str(datetime.now()), age, bp, bgr, bu, sc, hemo))
            conn.commit()

            # Report Download
            report_metrics = {"age": age, "bp": bp, "sc": sc, "hemo": hemo}
            pdf_data = generate_medical_pdf(st.session_state.username, prob, next_v, report_metrics)
            st.download_button("📩 Download PDF Medical Report", data=pdf_data, file_name=f"CKD_Report_{st.session_state.username}.pdf")
            st.success(f"📩 SMS reminder simulated for visit on {next_v}")

# =====================================================
# DOCTOR DASHBOARD
# =====================================================
def doctor_dashboard():
    st.title("👨‍⚕️ Clinical Supervisor Dashboard")
    data = pd.read_sql("SELECT * FROM predictions", conn)
    
    if not data.empty:
        m1, m2, m3 = st.columns(3)
        m1.metric("Patients Analyzed", len(data['username'].unique()))
        m2.metric("Critical Alerts", len(data[data['probability'] > 0.7]))
        m3.metric("Avg Severity", f"{data['probability'].mean()*100:.1f}%")
        
        st.subheader("Global Risk Trends")
        st.line_chart(data.set_index('created_at')['probability'])
        
        st.subheader("Full Clinical Registry")
        st.dataframe(data, use_container_width=True)
    else:
        st.info("No clinical records found.")

# =====================================================
# MAIN ROUTING
# =====================================================
if "logged_in" not in st.session_state: st.session_state.logged_in = False

if not st.session_state.logged_in:
    auth_page()
else:
    if st.session_state.role == "patient":
        patient_page()
    else:
        doctor_dashboard()


