import streamlit as st
import pandas as pd
import sqlite3
import hashlib
import os
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import joblib
import io

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

# =============================================
# PAGE CONFIG
# =============================================

st.set_page_config(
    page_title="AI CKD Hospital System",
    layout="wide",
    page_icon="🏥"
)

# =============================================
# HOSPITAL THEME
# =============================================

st.markdown("""
<style>

[data-testid="stSidebar"]{
background-color:#0e4c92;
}

[data-testid="stSidebar"] *{
color:white;
}

.main{
background-color:#f5f9ff;
}

h1,h2,h3{
color:#0e4c92;
}

</style>
""", unsafe_allow_html=True)

# =============================================
# DATABASE
# =============================================

DB_FILE="ckd_database.db"

conn=sqlite3.connect(DB_FILE,check_same_thread=False)
cursor=conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT UNIQUE,
password TEXT,
role TEXT,
phone TEXT,
created_at TEXT
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS predictions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT,
model_used TEXT,
probability REAL,
prediction INTEGER,
visit_number INTEGER,
next_visit TEXT,
created_at TEXT
)
""")

conn.commit()

# =============================================
# LANGUAGE SYSTEM
# =============================================

LANGUAGES={

"English":{
"about":"Chronic Kidney Disease is a long term condition where kidneys slowly lose function.",
"low":"Low CKD Risk",
"moderate":"Moderate CKD Risk",
"high":"High CKD Risk",
"download":"Download Medical Report"
},

"French":{
"about":"La maladie rénale chronique est une perte progressive de la fonction rénale.",
"low":"Risque faible",
"moderate":"Risque modéré",
"high":"Risque élevé",
"download":"Télécharger le rapport"
}

}

# =============================================
# PASSWORD HASH
# =============================================

def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

# =============================================
# LOAD ML MODELS
# =============================================

@st.cache_resource
def load_models():

    models={}

    if os.path.exists("ckd_random_forest.pkl"):
        models["Random Forest"]=joblib.load("ckd_random_forest.pkl")

    if os.path.exists("ckd_logistic.pkl"):
        models["Logistic Regression"]=joblib.load("ckd_logistic.pkl")

    scaler=None

    if os.path.exists("scaler.pkl"):
        scaler=joblib.load("scaler.pkl")

    return models,scaler

models,scaler=load_models()

# =============================================
# SEVERITY GRAPH
# =============================================

def show_severity(prob):

    percent=prob*100

    fig,ax=plt.subplots()

    ax.barh(["CKD Risk"],[percent])

    ax.set_xlim(0,100)

    ax.set_title("CKD Risk Severity")

    st.pyplot(fig)

    st.metric("Risk Probability",f"{percent:.2f}%")

# =============================================
# VISIT PREDICTION
# =============================================

def calculate_followup(prob,username):

    visit_count=cursor.execute(
    "SELECT COUNT(*) FROM predictions WHERE username=?",
    (username,)
    ).fetchone()[0]

    percent=prob*100

    if percent<30:
        days=180
    elif percent<70:
        days=30
    else:
        days=7

    next_visit=datetime.now()+timedelta(days=days)

    return visit_count+1,next_visit.date()

# =============================================
# SMS SIMULATION
# =============================================

def send_sms(username,next_visit):

    phone=cursor.execute(
    "SELECT phone FROM users WHERE username=?",
    (username,)
    ).fetchone()

    if phone and phone[0]:

        st.success(f"SMS Reminder sent to {phone[0]} for visit on {next_visit}")

# =============================================
# PDF REPORT
# =============================================

def generate_pdf(username,prob,next_visit):

    buffer=io.BytesIO()

    doc=SimpleDocTemplate(buffer)

    styles=getSampleStyleSheet()

    elements=[]

    elements.append(Paragraph("AI CKD Hospital Report",styles["Title"]))
    elements.append(Spacer(1,20))

    elements.append(Paragraph(f"Patient: {username}",styles["Normal"]))
    elements.append(Paragraph(f"Risk Probability: {prob*100:.2f}%",styles["Normal"]))
    elements.append(Paragraph(f"Next Visit: {next_visit}",styles["Normal"]))
    elements.append(Spacer(1,20))
    elements.append(Paragraph("Generated by AI CKD Hospital System",styles["Italic"]))

    doc.build(elements)

    buffer.seek(0)

    return buffer

# =============================================
# SESSION
# =============================================

if "logged_in" not in st.session_state:
    st.session_state.logged_in=False

# =============================================
# LOGIN PAGE
# =============================================

def login_page():

    st.title("🏥 AI CKD Hospital System")

    option=st.radio("Select Option",["Login","Register"])

    username=st.text_input("Username")
    password=st.text_input("Password",type="password")

    if option=="Register":

        role=st.selectbox("Role",["patient","doctor"])
        phone=st.text_input("Phone")

        if st.button("Register"):

            try:

                cursor.execute("""
                INSERT INTO users(username,password,role,phone,created_at)
                VALUES(?,?,?,?,?)
                """,(username,hash_password(password),role,phone,str(datetime.now())))

                conn.commit()

                st.success("Registration successful")

            except:

                st.error("Username already exists")

    if option=="Login":

        if st.button("Login"):

            user=cursor.execute("""
            SELECT * FROM users WHERE username=? AND password=?
            """,(username,hash_password(password))).fetchone()

            if user:

                st.session_state.logged_in=True
                st.session_state.username=user[1]
                st.session_state.role=user[3]

                st.rerun()

            else:

                st.error("Invalid credentials")

# =============================================
# PATIENT PAGE
# =============================================

def patient_page():

    st.sidebar.title("Patient Panel")

    if st.sidebar.button("Logout"):
        st.session_state.logged_in=False
        st.rerun()

    language=st.sidebar.selectbox("Language",list(LANGUAGES.keys()))
    text=LANGUAGES[language]

    st.title("CKD AI Risk Prediction")

    col1,col2,col3=st.columns(3)

    with col1:
        st.subheader("About CKD")
        st.write(text["about"])

    with col2:
        st.subheader("Causes")

        st.write("""
Diabetes  
High Blood Pressure  
Kidney Infection  
Genetic Disorders
""")

    with col3:
        st.subheader("Symptoms")

        st.write("""
Fatigue  
Swelling  
Urination Changes  
Nausea
""")

    st.markdown("---")

    model_choice=st.selectbox("Select AI Model",list(models.keys()))

    age=st.number_input("Age",1,120,40)
    bp=st.number_input("Blood Pressure",50,200,80)
    bgr=st.number_input("Blood Glucose",50,500,120)
    bu=st.number_input("Blood Urea",1,400,40)
    sc=st.number_input("Serum Creatinine",0.1,20.0,1.2)
    hemo=st.number_input("Hemoglobin",3.0,20.0,13.5)

    if st.button("Predict CKD Risk"):

        model=models[model_choice]

        df=pd.DataFrame([{
        "age":age,
        "bp":bp,
        "bgr":bgr,
        "bu":bu,
        "sc":sc,
        "hemo":hemo
        }])

        scaled=scaler.transform(df)

        prob=float(model.predict_proba(scaled)[0][1])

        show_severity(prob)

        visit_number,next_visit=calculate_followup(prob,st.session_state.username)

        cursor.execute("""
        INSERT INTO predictions
        (username,model_used,probability,prediction,visit_number,next_visit,created_at)
        VALUES(?,?,?,?,?,?,?)
        """,(st.session_state.username,model_choice,prob,1 if prob>0.5 else 0,
        visit_number,str(next_visit),str(datetime.now())))

        conn.commit()

        send_sms(st.session_state.username,next_visit)

        if prob<0.3:
            st.success(text["low"])
        elif prob<0.7:
            st.warning(text["moderate"])
        else:
            st.error(text["high"])

        pdf=generate_pdf(st.session_state.username,prob,next_visit)

        st.download_button(
        text["download"],
        pdf,
        "ckd_report.pdf"
        )

# =============================================
# DOCTOR DASHBOARD
# =============================================

def doctor_page():

    st.sidebar.title("Doctor Panel")

    if st.sidebar.button("Logout"):
        st.session_state.logged_in=False
        st.rerun()

    st.title("Hospital CKD Dashboard")

    data=pd.read_sql("SELECT * FROM predictions",conn)

    st.subheader("Patient Database")

    st.dataframe(data)

    st.subheader("Risk Distribution")

    st.bar_chart(data["probability"])

    st.subheader("Disease Progression")

    st.line_chart(data["probability"])

# =============================================
# ROUTING
# =============================================

if not st.session_state.logged_in:

    login_page()

else:

    if st.session_state.role=="patient":
        patient_page()

    else:
        doctor_page()
