# -*- coding: utf-8 -*-
"""chronic kidney disease project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NxUi6cZvGg2gZVUsKIfHC111t0u0fqF1

# **1. import necessary libraries**
"""

import pandas as pd
import numpy as np

from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, classification_report

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

import joblib

"""# **2.load dataset**"""

#uci dataset loading
chronic_kidney_disease = fetch_ucirepo(id=336)

X_uci = chronic_kidney_disease.data.features
y_uci = chronic_kidney_disease.data.targets

# Combine features + target
df_uci = pd.concat([X_uci, y_uci], axis=1)

df_uci.columns = df_uci.columns.str.lower().str.strip()

df_kaggle = pd.read_csv("/content/kidney_disease.csv")

df_kaggle.columns = df_kaggle.columns.str.lower().str.strip()

"""# **3. starndardize the target column**"""

df_uci["class"] = df_uci["class"].astype(str).str.lower().str.strip()
df_kaggle["classification"] = df_kaggle["classification"].astype(str).str.lower().str.strip()

label_map = {
    "ckd": 1,
    "notckd": 0,
    "ckd\t": 1,
    "notckd\t": 0
}

df_uci["class"] = df_uci["class"].replace(label_map)
df_kaggle["classification"] = df_kaggle["classification"].replace(label_map)

"""# **4. merge the two dataset**"""

df = pd.concat([df_uci, df_kaggle], ignore_index=True)

df.shape

"""# **5. split the feature target column**"""

X = df.drop(columns=["class"])
y = df["class"]

"""# **6. encode categorical columns**"""

cat_cols = X.select_dtypes(include="object").columns

for col in cat_cols:
    X[col] = X[col].astype(str)
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

"""# **6. handle missing values**"""

df.isnull().sum()

#impute for small data
imputer = SimpleImputer(strategy="mean")
X = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

# Remove NaN labels
mask = y.notna()
X = X.loc[mask]
y = y.loc[mask]

df.isnull().sum()

"""## **7. split the data set**"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""# **9. load the model**"""

model = Sequential([
    Dense(128, activation="relu", input_shape=(X_train.shape[1],)),
    Dropout(0.3),

    Dense(64, activation="relu"),
    Dropout(0.2),

    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

"""# **10. train the model[link text](https://)**"""

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

y_pred = (model.predict(X_test) > 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt

# Loss
plt.figure(figsize=(8,5))
plt.plot(history.history["loss"], label="Train Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("DNN Training vs Validation Loss")
plt.legend()
plt.show()

# Accuracy
plt.figure(figsize=(8,5))
plt.plot(history.history["accuracy"], label="Train Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("DNN Training vs Validation Accuracy")
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Not CKD", "CKD"]
)

disp.plot(cmap="Blues")
plt.title("Confusion Matrix – CKD DNN Model")
plt.show()

from sklearn.inspection import permutation_importance
from sklearn.metrics import accuracy_score

# Define a custom scoring function that permutation_importance can use
def custom_accuracy_scorer(estimator, X, y_true):
    # Keras model.predict returns probabilities, so we need to threshold them
    y_pred_proba = estimator.predict(X, verbose=0)
    y_pred = (y_pred_proba > 0.5).astype(int)
    return accuracy_score(y_true, y_pred)

# Pass this custom function directly as the scoring argument
r = permutation_importance(model, X_test, y_test, n_repeats=30, random_state=42, scoring=custom_accuracy_scorer)

importance_df = pd.DataFrame({
    'feature': X.columns,
    'importance': r.importances_mean
}).sort_values(by='importance', ascending=False)

plt.figure(figsize=(8, 6))
plt.barh(
    importance_df["feature"][:10],
    importance_df["importance"][:10]
)
plt.gca().invert_yaxis()
plt.xlabel("Permutation Importance")
plt.title("Top 10 Important Features (DNN)")
plt.show()

!pip install shap
import shap

explainer = shap.Explainer(model, X_train)
shap_values = explainer(X_test[:100])

shap.summary_plot(shap_values, X_test[:100], feature_names=X.columns)

import shap

# Use small background set for speed
background = X_train[:100]

explainer = shap.KernelExplainer(
    model.predict,
    background
)

shap_values = explainer.shap_values(X_test[:50])
shap.summary_plot(
    shap_values,
    X_test[:50],
    feature_names=X.columns
)

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred_rf = rf_model.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

import pandas as pd

rf_importance = pd.DataFrame({
    "feature": X.columns,
    "importance": rf_model.feature_importances_
}).sort_values(by="importance", ascending=False)

rf_importance.head(10)

plt.figure(figsize=(8,6))
plt.barh(
    rf_importance["feature"].head(15),
    rf_importance["importance"].head(15)
)
plt.gca().invert_yaxis()
plt.xlabel("Importance Score")
plt.title("Top 15 Feature Importances – Random Forest")
plt.show()

from sklearn.metrics import precision_score, recall_score, f1_score

comparison = pd.DataFrame({
    "Model": ["DNN", "Random Forest"],
    "Accuracy": [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, y_pred_rf)
    ],
    "Recall (CKD)": [
        recall_score(y_test, y_pred),
        recall_score(y_test, y_pred_rf)
    ],
    "F1 Score": [
        f1_score(y_test, y_pred),
        f1_score(y_test, y_pred_rf)
    ]
})

comparison

"""# **model save**"""

model.save("ckd_dnn_model.keras")
joblib.dump(scaler, "scaler.pkl")

import joblib

joblib.dump(rf_model, "ckd_random_forest.pkl")